# Generated by ChatGPT for stepF (DB personalization)
from django.db import migrations, models
import django.db.models.deletion
from django.core.validators import MinValueValidator, MaxValueValidator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("is_superuser", models.BooleanField(default=False, help_text="Designates that this user has all permissions without explicitly assigning them.", verbose_name="superuser status")),
                ("username", models.CharField(error_messages={"unique": "A user with that username already exists."}, help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.", max_length=150, unique=True, verbose_name="username")),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="이메일")),
                ("is_staff", models.BooleanField(default=False, help_text="Designates whether the user can log into this admin site.", verbose_name="staff status")),
                ("is_active", models.BooleanField(default=True, help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.", verbose_name="active")),
                ("date_joined", models.DateTimeField(auto_now_add=True, verbose_name="date joined")),
                ("profile_image", models.ImageField(blank=True, null=True, upload_to="profiles/", verbose_name="프로필 이미지")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="가입일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("total_trips", models.PositiveIntegerField(default=0, verbose_name="총 여행 수")),
                ("total_countries", models.PositiveIntegerField(default=0, verbose_name="방문 국가 수")),
                ("total_cities", models.PositiveIntegerField(default=0, verbose_name="방문 도시 수")),
                ("groups", models.ManyToManyField(blank=True, help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.", related_name="user_set", related_query_name="user", to="auth.group", verbose_name="groups")),
                ("user_permissions", models.ManyToManyField(blank=True, help_text="Specific permissions for this user.", related_name="user_set", related_query_name="user", to="auth.permission", verbose_name="user permissions")),
            ],
            options={"verbose_name": "사용자", "verbose_name_plural": "사용자들"},
        ),
        migrations.CreateModel(
            name="TravelPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("travel_style", models.CharField(choices=[("relaxed", "여유로운 휴식"), ("active", "활동적인 탐험"), ("cultural", "문화/역사 탐방"), ("foodie", "미식 여행"), ("adventure", "모험/액티비티"), ("shopping", "쇼핑 중심"), ("nature", "자연/힐링"), ("mixed", "골고루")], default="mixed", max_length=20, verbose_name="여행 스타일")),
                ("budget_level", models.CharField(choices=[("budget", "가성비 (저예산)"), ("moderate", "적당한 예산"), ("comfort", "편안한 여행"), ("luxury", "럭셔리")], default="moderate", max_length=20, verbose_name="예산 수준")),
                ("accommodation_preference", models.CharField(choices=[("hostel", "호스텔/게스트하우스"), ("hotel_budget", "저가 호텔"), ("hotel_mid", "중급 호텔"), ("hotel_luxury", "고급 호텔"), ("airbnb", "에어비앤비"), ("resort", "리조트")], default="hotel_mid", max_length=20, verbose_name="숙소 선호")),
                ("landmark_preference", models.PositiveSmallIntegerField(default=8, help_text="유명 명소 방문 선호도", validators=[MinValueValidator(1), MaxValueValidator(10)], verbose_name="랜드마크 선호도")),
                ("local_experience_preference", models.PositiveSmallIntegerField(default=5, help_text="현지인처럼 여행하기 선호도", validators=[MinValueValidator(1), MaxValueValidator(10)], verbose_name="로컬 체험 선호도")),
                ("food_preference", models.PositiveSmallIntegerField(default=7, help_text="맛집/미슐랭 탐방 선호도", validators=[MinValueValidator(1), MaxValueValidator(10)], verbose_name="미식 선호도")),
                ("nature_preference", models.PositiveSmallIntegerField(default=5, validators=[MinValueValidator(1), MaxValueValidator(10)], verbose_name="자연 선호도")),
                ("museum_preference", models.PositiveSmallIntegerField(default=5, validators=[MinValueValidator(1), MaxValueValidator(10)], verbose_name="박물관/미술관 선호도")),
                ("shopping_preference", models.PositiveSmallIntegerField(default=4, validators=[MinValueValidator(1), MaxValueValidator(10)], verbose_name="쇼핑 선호도")),
                ("nightlife_preference", models.PositiveSmallIntegerField(default=3, validators=[MinValueValidator(1), MaxValueValidator(10)], verbose_name="나이트라이프 선호도")),
                ("daily_poi_count", models.PositiveSmallIntegerField(default=4, help_text="하루에 방문하고 싶은 장소 수", validators=[MinValueValidator(2), MaxValueValidator(8)], verbose_name="하루 방문 장소 수")),
                ("walking_tolerance", models.PositiveSmallIntegerField(default=6, help_text="많이 걷는 것에 대한 선호도", validators=[MinValueValidator(1), MaxValueValidator(10)], verbose_name="도보 이동 선호도")),
                ("early_bird", models.BooleanField(default=False, help_text="아침 일정 선호", verbose_name="아침형 여행자")),
                ("needs_breaks", models.BooleanField(default=True, help_text="중간 휴식/카페 포함 선호", verbose_name="휴식 필요")),
                ("avoid_crowds", models.BooleanField(default=False, help_text="혼잡한 장소 회피 선호", verbose_name="혼잡 회피")),
                ("prefer_public_transport", models.BooleanField(default=True, help_text="대중교통 선호", verbose_name="대중교통 선호")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="travel_preference", to="accounts.user", verbose_name="사용자")),
            ],
            options={"verbose_name": "여행 선호도", "verbose_name_plural": "여행 선호도"},
        ),
        migrations.CreateModel(
            name="UserAIMemory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("memories", models.JSONField(blank=True, default=list, verbose_name="메모리")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="ai_memory", to="accounts.user", verbose_name="사용자")),
            ],
            options={"verbose_name": "AI 메모리", "verbose_name_plural": "AI 메모리"},
        ),
        migrations.CreateModel(
            name="UserChatSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day_number", models.PositiveSmallIntegerField(default=1, verbose_name="일차")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("travel_plan", models.IntegerField(blank=True, null=True, db_index=True, db_column="travel_plan_id", verbose_name="여행 계획")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chat_sessions", to="accounts.user", verbose_name="사용자")),
            ],
            options={"verbose_name": "AI 채팅 세션", "verbose_name_plural": "AI 채팅 세션", "ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="UserChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("user", "User"), ("assistant", "Assistant")], max_length=20, verbose_name="역할")),
                ("content", models.TextField(verbose_name="내용")),
                ("sources", models.JSONField(blank=True, default=list, verbose_name="근거")),
                ("actions", models.JSONField(blank=True, default=list, verbose_name="액션")),
                ("used_llm", models.BooleanField(default=False, verbose_name="LLM 사용")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="accounts.userchatsession", verbose_name="세션")),
            ],
            options={"verbose_name": "AI 채팅 메시지", "verbose_name_plural": "AI 채팅 메시지", "ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="UserBehaviorEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day_number", models.PositiveSmallIntegerField(default=1, verbose_name="일차")),
                ("event_type", models.CharField(max_length=50, verbose_name="이벤트 타입")),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="페이로드")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("travel_plan", models.IntegerField(blank=True, null=True, db_index=True, db_column="travel_plan_id", verbose_name="여행 계획")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="behavior_events", to="accounts.user", verbose_name="사용자")),
            ],
            options={"verbose_name": "행동 이벤트", "verbose_name_plural": "행동 이벤트", "ordering": ["-created_at"]},
        ),
    ]
