# Generated by Django 4.2.28 on 2026-02-10 04:07

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="travelpreference",
            options={"verbose_name": "여행 선호도", "verbose_name_plural": "여행 선호도들"},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="travelpreference",
            name="needs_breaks",
        ),
        migrations.RemoveField(
            model_name="travelpreference",
            name="prefer_public_transport",
        ),
        migrations.AddField(
            model_name="travelpreference",
            name="accessibility_required",
            field=models.BooleanField(
                default=False, help_text="휠체어 접근 등", verbose_name="접근성 필요"
            ),
        ),
        migrations.AddField(
            model_name="travelpreference",
            name="halal_required",
            field=models.BooleanField(default=False, verbose_name="할랄 음식 필요"),
        ),
        migrations.AddField(
            model_name="travelpreference",
            name="local_food_preference",
            field=models.BooleanField(default=True, verbose_name="현지 음식 선호"),
        ),
        migrations.AddField(
            model_name="travelpreference",
            name="michelin_preference",
            field=models.BooleanField(default=True, verbose_name="미슐랭 레스토랑 선호"),
        ),
        migrations.AddField(
            model_name="travelpreference",
            name="vegetarian",
            field=models.BooleanField(default=False, verbose_name="채식주의자"),
        ),
        migrations.AlterField(
            model_name="travelpreference",
            name="avoid_crowds",
            field=models.BooleanField(default=False, verbose_name="붐비는 곳 피하기"),
        ),
        migrations.AlterField(
            model_name="travelpreference",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="travelpreference",
            name="early_bird",
            field=models.BooleanField(
                default=False, help_text="이른 아침 일정 선호", verbose_name="아침형 여행자"
            ),
        ),
        migrations.AlterField(
            model_name="travelpreference",
            name="nature_preference",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="자연/공원 방문 선호도",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="자연 선호도",
            ),
        ),
        migrations.AlterField(
            model_name="travelpreference",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
        migrations.CreateModel(
            name="VisitedPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_name", models.CharField(max_length=200, verbose_name="장소명")),
                (
                    "place_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Google Place ID"
                    ),
                ),
                ("place_type", models.CharField(max_length=50, verbose_name="장소 타입")),
                (
                    "feature",
                    models.CharField(blank=True, max_length=50, verbose_name="카테고리"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="도시")),
                ("country", models.CharField(max_length=100, verbose_name="국가")),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="위도"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="경도"),
                ),
                (
                    "user_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        verbose_name="사용자 평점",
                    ),
                ),
                ("liked", models.BooleanField(default=True, verbose_name="좋아요")),
                (
                    "would_revisit",
                    models.BooleanField(default=True, verbose_name="재방문 의사"),
                ),
                (
                    "visited_at",
                    models.DateField(blank=True, null=True, verbose_name="방문일"),
                ),
                (
                    "visit_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="체류 시간(분)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="메모")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="기록일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visited_places",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "방문 장소",
                "verbose_name_plural": "방문 장소들",
                "ordering": ["-visited_at", "-created_at"],
                "unique_together": {("user", "place_id")},
            },
        ),
        migrations.CreateModel(
            name="FavoriteCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="도시")),
                ("country", models.CharField(max_length=100, verbose_name="국가")),
                (
                    "visit_count",
                    models.PositiveIntegerField(default=1, verbose_name="방문 횟수"),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="평점",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_cities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "관심 도시",
                "verbose_name_plural": "관심 도시들",
                "unique_together": {("user", "city", "country")},
            },
        ),
    ]
