# Generated by Django 4.2.28 on 2026-02-09 07:17

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="이메일"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profiles/",
                        verbose_name="프로필 이미지",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="가입일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "total_trips",
                    models.PositiveIntegerField(default=0, verbose_name="총 여행 수"),
                ),
                (
                    "total_countries",
                    models.PositiveIntegerField(default=0, verbose_name="방문 국가 수"),
                ),
                (
                    "total_cities",
                    models.PositiveIntegerField(default=0, verbose_name="방문 도시 수"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자들",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="TravelPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "travel_style",
                    models.CharField(
                        choices=[
                            ("relaxed", "여유로운 휴식"),
                            ("active", "활동적인 탐험"),
                            ("cultural", "문화/역사 탐방"),
                            ("foodie", "미식 여행"),
                            ("adventure", "모험/액티비티"),
                            ("shopping", "쇼핑 중심"),
                            ("nature", "자연/힐링"),
                            ("mixed", "골고루"),
                        ],
                        default="mixed",
                        max_length=20,
                        verbose_name="여행 스타일",
                    ),
                ),
                (
                    "budget_level",
                    models.CharField(
                        choices=[
                            ("budget", "가성비 (저예산)"),
                            ("moderate", "적당한 예산"),
                            ("comfort", "편안한 여행"),
                            ("luxury", "럭셔리"),
                        ],
                        default="moderate",
                        max_length=20,
                        verbose_name="예산 수준",
                    ),
                ),
                (
                    "accommodation_preference",
                    models.CharField(
                        choices=[
                            ("hostel", "호스텔/게스트하우스"),
                            ("hotel_budget", "저가 호텔"),
                            ("hotel_mid", "중급 호텔"),
                            ("hotel_luxury", "고급 호텔"),
                            ("airbnb", "에어비앤비"),
                            ("resort", "리조트"),
                        ],
                        default="hotel_mid",
                        max_length=20,
                        verbose_name="숙소 선호",
                    ),
                ),
                (
                    "landmark_preference",
                    models.PositiveSmallIntegerField(
                        default=8,
                        help_text="유명 명소 방문 선호도",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="랜드마크 선호도",
                    ),
                ),
                (
                    "local_experience_preference",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="현지인처럼 여행하기 선호도",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="로컬 체험 선호도",
                    ),
                ),
                (
                    "food_preference",
                    models.PositiveSmallIntegerField(
                        default=7,
                        help_text="맛집/미슐랭 탐방 선호도",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="미식 선호도",
                    ),
                ),
                (
                    "nature_preference",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="자연/공원 방문 선호도",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="자연 선호도",
                    ),
                ),
                (
                    "museum_preference",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="박물관/미술관 선호도",
                    ),
                ),
                (
                    "shopping_preference",
                    models.PositiveSmallIntegerField(
                        default=4,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="쇼핑 선호도",
                    ),
                ),
                (
                    "nightlife_preference",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="나이트라이프 선호도",
                    ),
                ),
                (
                    "daily_poi_count",
                    models.PositiveSmallIntegerField(
                        default=4,
                        help_text="하루에 방문하고 싶은 장소 수",
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(8),
                        ],
                        verbose_name="하루 방문 장소 수",
                    ),
                ),
                (
                    "walking_tolerance",
                    models.PositiveSmallIntegerField(
                        default=6,
                        help_text="많이 걷는 것에 대한 선호도",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="도보 이동 선호도",
                    ),
                ),
                (
                    "early_bird",
                    models.BooleanField(
                        default=False, help_text="이른 아침 일정 선호", verbose_name="아침형 여행자"
                    ),
                ),
                (
                    "michelin_preference",
                    models.BooleanField(default=True, verbose_name="미슐랭 레스토랑 선호"),
                ),
                (
                    "local_food_preference",
                    models.BooleanField(default=True, verbose_name="현지 음식 선호"),
                ),
                (
                    "vegetarian",
                    models.BooleanField(default=False, verbose_name="채식주의자"),
                ),
                (
                    "halal_required",
                    models.BooleanField(default=False, verbose_name="할랄 음식 필요"),
                ),
                (
                    "avoid_crowds",
                    models.BooleanField(default=False, verbose_name="붐비는 곳 피하기"),
                ),
                (
                    "accessibility_required",
                    models.BooleanField(
                        default=False, help_text="휠체어 접근 등", verbose_name="접근성 필요"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "여행 선호도",
                "verbose_name_plural": "여행 선호도들",
            },
        ),
        migrations.CreateModel(
            name="VisitedPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_name", models.CharField(max_length=200, verbose_name="장소명")),
                (
                    "place_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Google Place ID"
                    ),
                ),
                ("place_type", models.CharField(max_length=50, verbose_name="장소 타입")),
                (
                    "feature",
                    models.CharField(blank=True, max_length=50, verbose_name="카테고리"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="도시")),
                ("country", models.CharField(max_length=100, verbose_name="국가")),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="위도"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="경도"),
                ),
                (
                    "user_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        verbose_name="사용자 평점",
                    ),
                ),
                ("liked", models.BooleanField(default=True, verbose_name="좋아요")),
                (
                    "would_revisit",
                    models.BooleanField(default=True, verbose_name="재방문 의사"),
                ),
                (
                    "visited_at",
                    models.DateField(blank=True, null=True, verbose_name="방문일"),
                ),
                (
                    "visit_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="체류 시간(분)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="메모")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="기록일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visited_places",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "방문 장소",
                "verbose_name_plural": "방문 장소들",
                "ordering": ["-visited_at", "-created_at"],
                "unique_together": {("user", "place_id")},
            },
        ),
        migrations.CreateModel(
            name="FavoriteCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="도시")),
                ("country", models.CharField(max_length=100, verbose_name="국가")),
                (
                    "visit_count",
                    models.PositiveIntegerField(default=1, verbose_name="방문 횟수"),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="평점",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_cities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "관심 도시",
                "verbose_name_plural": "관심 도시들",
                "unique_together": {("user", "city", "country")},
            },
        ),
    ]
